name: MLflow CI Advanced

on:
  push:
    branches:
      - main

jobs:
  train-model:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: "3.11"
          activate-environment: mlflow-env

      - name: Install dependencies
        shell: bash -l {0}
        run: |
          pip install mlflow pandas scikit-learn joblib

      - name: Run MLflow Project
        shell: bash -l {0}
        working-directory: ./MLProject
        run: |
          mlflow run .

      - name: Check generated files
        shell: bash -l {0}
        working-directory: ./MLProject
        run: |
          pwd
          ls -lah
          ls -lah artifacts || true
          ls -R mlruns || true

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: titanic-model
          if-no-files-found: error
          path: |
            MLProject/artifacts/**
            MLProject/mlruns/**

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Find MLflow model path
        id: modelpath
        shell: bash -l {0}
        working-directory: ./MLProject
        run: |
          MODEL_PATH=$(find mlruns -name MLmodel | head -n 1 | xargs dirname)

          echo "Found model at $MODEL_PATH"

          echo "MODEL_PATH=$MODEL_PATH" >> $GITHUB_ENV

      - name: Build Docker image
        shell: bash -l {0}
        working-directory: ./MLProject
        run: |
          mlflow models build-docker \
            -m "$MODEL_PATH" \
            -n ${{ secrets.DOCKER_USERNAME }}/titanic-mlflow

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/titanic-mlflow:latest
